ekf_filter_node:
  ros__parameters:
    frequency: 30.0
    sensor_timeout: 0.5
    two_d_mode: true

    # Frame IDs
    map_frame: map
    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom

    publish_tf: true

    # # IMU Configuration
    # imu0: /imu/filtered
    # imu0_config: [false, false, false,
    #               true,  true,  true,
    #               false,  false,  false,
    #               false, false, true]

    # imu0_differential: false
    # imu0_remove_gravitational_acceleration: true

    # SLAM Pose Input
    odom0: /slam_toolbox/pose
    odom0_config: [true,  true,  false,
                   false, false, true,
                   false, false, false,
                   false, false, false]
    odom0_differential: false

    # ✅ NEW: Leg Odometry Input
    odom1: /odom/leg
    odom1_config: [true,  true,  false,   # x, y, z
                   false, false, true,   # roll, pitch, yaw
                   false, false, false,  # vx, vy, vz (not published)
                   false, false, false,  # vroll, vpitch, vyaw
                   false, false, false]  # ax, ay, az
    odom1_differential: false
    odom1_relative: false
