slam_toolbox:
  ros__parameters:
    use_sim_time: false
    mode: mapping
    resolution: 0.05
    scan_topic: /scan
    scan_queue_size: 100
    base_frame: base_link
    map_frame: map
    odom_frame: odom
    imu_topic: /imu/filtered
    use_imu: true
    start_trajectory_with_default_topics: true
