slam_toolbox:
  ros__parameters:
    # General
    use_sim_time: false
    mode: mapping
    start_trajectory_with_default_topics: true
    resolution: 0.05
    base_frame: base_link
    map_frame: map
    odom_frame: odom
    publish_tf: true
    transform_publish_period: 0.05
    map_publish_period: 1.0

    # Laser settings
    scan_topic: /scan
    scan_queue_size: 100

    # IMU
    use_imu: true
    imu_topic: /imu/filtered

    # Optimization & Backend
    use_scan_matching: true
    minimum_travel_distance: 0.2
    minimum_travel_heading: 0.1
    transform_timeout: 0.2
    map_update_interval: 2.0

    # Pose Graph parameters
    max_laser_range: 20.0
    minimum_time_interval: 0.5
    transform_timeout: 0.5
    tf_buffer_duration: 30.0

    # Loop closure
    enable_loop_closure: true
    loop_match_method: "scan_matching"
    loop_closure_min_score: 0.3
    loop_closure_max_distance: 10.0
    loop_closure_min_chain_size: 10

    # Serialization (optional)
    serialization_time_interval: 30.0
    serialization_format: "binary"
